services:
  postgres_DB:
    container_name: postgres_DB
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tgdd_db
    volumes:
      - ./db/init_db/:/docker-entrypoint-initdb.d/:ro
      - ./db/postgres_data/:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:latest
    ports: 
      - 80:80
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf

  data_crawling:
    container_name: data_crawling
    build: 
      context: ./data_crawling/
      dockerfile: Dockerfile
    image: data_crawling  
    ports:
     - 8000:8000
    volumes:
     - ./data_crawling/logs/:/base/data_crawling/logs
     - ./landing_zone/:/base/landing_zone/
    depends_on:
     - data_ingestion


  data_ingestion:
    container_name: data_ingestion
    build:
      context: ./data_ingestion/
      dockerfile: Dockerfile
    image: data_ingestion
    ports:
     - 8001:8001
    volumes:
     - ./data_ingestion/logs/:/base/data_ingestion/logs
     - ./landing_zone/:/base/landing_zone/
    depends_on:
     - database_api

  database_api:
    container_name: database_api
    build:
      context: ./database_api/
    image: database_api
    ports:
     - 8002:8002
    volumes:
     - ./database_api/logs/:/base/database_api/logs/
    depends_on:
      - postgres_DB

    

